name: deploy
on:
  push:
    branches:
      - master
jobs:
  packer:
    runs-on: ubuntu-latest
    env:
      PKR_VAR_digitalocean_api_token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
    steps:
      - name: Set environment variable PKR_VAR_digitalocean_snapshot_name
        run: echo ::set-env name=PKR_VAR_digitalocean_snapshot_name::pkr-${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7}
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Packer build
        uses: kologicdev/github-action-get-packer-ansible@master
        with:
          args: build -on-error=abort ./packer
  terraform:
    needs: packer
    runs-on: ubuntu-latest
    env:
      TF_version: latest
      TF_working_dir: "./terraform/"
      TF_VAR_BACKEND_digitalocean_spaces_bucket: ${{ secrets.DIGITALOCEAN_SPACES_BUCKET }}
      TF_VAR_BACKEND_digitalocean_spaces_access_key: ${{ secrets.DIGITALOCEAN_SPACES_ACCESS_KEY }}
      TF_VAR_BACKEND_digitalocean_spaces_secret_key: ${{ secrets.DIGITALOCEAN_SPACES_SECRET_KEY }}
      TF_VAR_digitalocean_api_token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      TF_VAR_digitalocean_public_ssh_key_name: ${{ secrets.DIGITALOCEAN_PUBLIC_SSH_KEY_NAME }}
      TF_VAR_digitalocean_domain_name: ${{ secrets.DIGITALOCEAN_DOMAIN_NAME }}
    steps:
      - name: Set environment variable TF_VAR_BACKEND_digitalocean_spaces_key
        run: echo ::set-env name=TF_VAR_BACKEND_digitalocean_spaces_key::${GITHUB_REPOSITORY#*/}/${GITHUB_REF#refs/heads/}/terraform.tfstate
      - name: Set environment variable TF_VAR_BACKEND_digitalocean_instance_name
        run: echo ::set-env name=TF_VAR_digitalocean_instance_name::${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7}
      - name: Set environment variable TF_VAR_digitalocean_image_name
        run: echo ::set-env name=TF_VAR_digitalocean_image_name::pkr-${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7}
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Terraform format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: fmt
      - name: Terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: init
          args:
            -backend-config="key=${{ env.TF_VAR_BACKEND_digitalocean_spaces_key }}"
            -backend-config="bucket=${{ env.TF_VAR_BACKEND_digitalocean_spaces_bucket }}"
            -backend-config="access_key=${{ env.TF_VAR_BACKEND_digitalocean_spaces_access_key }}"
            -backend-config="secret_key=${{ env.TF_VAR_BACKEND_digitalocean_spaces_secret_key }}"
      - name: Terraform validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: validate
      - name: Terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: plan
          args:
            -out "${GITHUB_SHA:0:7}.tfplan"
      - name: Terraform apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_version }}
          tf_actions_working_dir: ${{ env.TF_working_dir }}
          tf_actions_subcommand: apply
          args:
            "${GITHUB_SHA:0:7}.tfplan"
